### ISSUE TITLE
Error on building

### ISSUE THREAD

**Issue by vcapretz** [entria/koa-passport-mongoose-graphql#21]
I just forked the repo and when building it for the first time (after running `npm i`) I faced an error: 
![image](https://user-images.githubusercontent.com/14620121/28586072-e397e83a-7148-11e7-9bb4-65cb207c1a69.png)

Apparently it's because the lodash's version used in the _async_ module, but I'm not figuring out what other package uses _async_  as a dependency.

Any thoughts? Probably it's just updating some package, just need to know which one :smile:

**Comment by sibelius** [comment]
could you try to upgrade the deps and see if it fixes it?

**Comment by sibelius** [comment]
try to use `yarn why` https://yarnpkg.com/lang/en/docs/cli/why/

**Comment by vcapretz** [comment]
```sh
   - "mongoose-fill" depends on it
   - "supertest#superagent#form-data" depends on it
``` 

But running `yarn` instead of `npm i` to install the deps don't throw the same error, weird! haha 

I was able to run the project now!

**Comment by sibelius** [comment]
hm, we should remove mongoose-fill, it is not relevant anymore

**Comment by MarianVasile** [comment]
We can close this one.

**Comment by sibelius** [comment]
sure
