### ISSUE TITLE
import bug in version change

### ISSUE THREAD

**Issue by IEfucker** [entria/koa-passport-mongoose-graphql#25]
bug report:

connect dataBase function has been changed to a default export,
https://github.com/entria/koa-passport-mongoose-graphql/blob/master/src/server/db/index.js#L3

but here, curly brackets in import statement is unnecessary
https://github.com/entria/koa-passport-mongoose-graphql/blob/master/src/index.js#L4

**Comment by MarkVasile** [comment]
Thank you Jack, fixed that and the graphql import too. Good catch.
